loko/blueprints/auth.py
import os
from flask import Blueprint, render_template, redirect, flash, url_for, request
from loko.blueprints.index import index_blueprint
from loko.models import get_db_session, models
from loko.forms import RegistrationForm, LoginForm
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.urls import url_parse

auth_blueprint = Blueprint('auth_blueprint', __name__)
env = os.environ['FLASK_ENV']
session = get_db_session(env=env)

@auth_blueprint.route('/login', methods=['GET','POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('index_blueprint.landing'))
	form = LoginForm()
	if form.validate_on_submit():
		username = form.username.data
		password = form.password.data
		user = session.query(models.Users).\
					  filter(models.Users.username == username.lower()).\
									  one_or_none()

		if user is None or not user.check_password(password):
			flash('Invalid username or password')
			return redirect(url_for('auth_blueprint.login'))
		
		login_user(user, remember=form.remember_me.data)
		next_page = request.args.get('next')
		if not next_page or url_parse(next_page).netloc != '':
			next_page = url_for('index_blueprint.landing')
		return redirect(next_page)
	return render_template('login.html', title='Sign In', form=form, current_user=current_user)

@auth_blueprint.route('/logout')
@login_required
def logout():
	logout_user()
	return redirect(url_for('index_blueprint.landing'))

@auth_blueprint.route('/register', methods=['GET','POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('index_blueprint.landing'))
	form = RegistrationForm()
	if form.validate_on_submit():
		user = models.Users(username=form.username.data.lower(), name=form.name.data, email=form.email.data,default_currency_alpha_code=form.currency.data,authenticated=False,active=True)
		user.set_password(form.password.data)
		session.add(user)
		session.flush()
		wallet = models.Wallets(ownerid=user.id, currency_alpha_code=user.default_currency_alpha_code, balance=float(form.starting_balance.data))
		session.add(wallet)
		session.commit()
		flash('Congratulations, you are now a registered user!')
		return redirect(url_for('auth_blueprint.login'))
	return render_template('register.html', form=form, current_user=current_user, title='Register')


loko/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto&display=swap" > 
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
        <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
        <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css') }}">
        {% if title %}
        <title>{{ title }} | loko</title>
        {% else %}
        <title>loko</title>
        {% endif %}
    </head>
    <body>
        <section class = "header hero is-primary">
            <div class="hero-head">            
                <nav class = "navbar">
                    <div class="container">
                        <div class="navbar-brand">
                            <a href="{{ url_for('index_blueprint.landing') }}" class="navbar-item is-inverted">
                                loko
                            </a>
                            <span class="navbar-burger burger" data-target="navbarMenuHeroA">
                            <span></span>
                            <span></span>
                            <span></span>
                            </span>
                        </div>
                        <div id="navbarMenuHeroA" class="navbar-menu">
                            <div class="navbar-end">
                                <a class="navbar-item" href="{{ url_for('index_blueprint.landing') }}">Home</a>
                                {% if current_user.is_authenticated %}
                                <a class="navbar-item" href="{{ url_for('auth_blueprint.logout') }}">Logout {{current_user.username}}</a>
                                {% else %}
                                <a class="navbar-item" href="{{ url_for('auth_blueprint.login') }}">Login</a>
                                {% endif %}                            
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </section>
        <!-- <hr> -->
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="container">
                    <div class="notification">
                        <ul>
                            {% for message in messages %}
                            <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
        {% endif %}
        {% endwith %}
        <section class= "section main">
        {% block content %} {% endblock %}
        </section>
        <!-- <hr> -->
        <section class="footer">
            <p>loko &copy; 2021</p>
        </section>
    </body>
</html>

loko/templates/index.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" href="{{url_for('static', filename='css/landing_styles.css') }}">
<div class="main-canvas columns">
	<div class="inner-canvas column is-three-fifths is-offset-one-fifth">
		<div class="info-block box">
			<div class="acct-info">
				<div class="user-details columns">
					<div class="column is-four-fifths">
						<div class="notification is-black has-text-white ">
							<p class="is-size-4">{{current_user.name}}</p> 
						</div>
					</div>
					<div class="column is-one-fifth">
						<div class="notification is-white">
							<span class="icon prof-pic">
								<i class="fas fa-4x fa-user-circle"></i>
							</span>
						</div>
					</div>
				</div>
				<div class="columns is-centered acc-bal-details">
					<div class="column is-6">
						<div class="card">
							<div class="card-header">
								<span class="card-header-title has-text-centered">Account Balance</span> 
							</div>
							<div id="acct_balance" class="card-content  has-text-centered">
								<p class="bd-notification is-primary">{{wallet['currency_alpha_code']}} {{wallet['display balance']}}</p> 
							</div> 
						</div>
					</div>
					</div>
				</div>
				
			<div class="footer columns">
				<div class="column is-3 is-offset-2">
					<button id="send-money-btn" class="button is-rounded is-link">
						<span class="icon">
					    	<i class="fas fa-money-bill-wave"></i>
						</span>
						<span>Send Money</span>
					</button>
				</div>
				<div class="column is-3 is-offset-1">
					<button id="change-acc-curr-btn"class="button is-rounded is-info"><span class="icon">
					    	<i class="fas fa-money-check-alt"></i>
						</span>
						<span>Account currency</span>
					</button>
				</div>
			</div>
			
		</div>
		<div class="history-block box">
			Show Past transactions here
		</div>
	</div>
</div>
<!-- Modal for sending money -->
<div id = "mod-sendmoney" class="modal is-active"> 
	<div class="modal-background"></div>
	<div class="modal-card">
		<header class="modal-card-head">
			<p class="modal-card-title">Send Money</p>
			<button class="delete close-modal" aria-label="close"></button>
		</header>
		<section class="modal-card-body">
			<form action="/sendmoney" method="post" novalidate>
			{{sendmoney_form.hidden_tag()}}
				<div class="field">
					{{sendmoney_form.recipient_email.label}}
					<div class="control">
						{{ sendmoney_form.recipient_email(size=32, class="input") }}
					</div>
					{% for error in sendmoney_form.recipient_email.errors %}
					<span style="color: red;">[{{ error }}]</span>
					{% endfor %}
				</div>
				<div class="columns">
					<div class="field column is-three-fifths">
						{{sendmoney_form.amount.label}}
						<div class="control">
							{{ sendmoney_form.amount(size=32, class="input") }}
						</div>
						{% for error in sendmoney_form.amount.errors %}
						<span style="color: red;">[{{ error }}]</span>
						{% endfor %}
					</div>

					<div class="field column is-one-fifth">
						{{sendmoney_form.currency.label}}
						<div class="select">
							{{ sendmoney_form.currency() }}
						</div>
						{% for error in sendmoney_form.currency.errors %}
						<span style="color: red;">[{{ error }}]</span>
						{% endfor %}
					</div>
				</div>
				

				<div class="field">
					{{sendmoney_form.password.label}}
					<div class="control">
						{{ sendmoney_form.password(size=32, class="input") }}
					</div>
					{% for error in sendmoney_form.password.errors %}
					<span style="color: red;">[{{ error }}]</span>
					{% endfor %}
				</div>
			</form>
		</section>
		<footer class="modal-card-foot">
			<button class="button submit-sendmoney submit-form is-success">Send money</button>
			<button class="button close-modal">Cancel</button>
		</footer>
	</div>
</div>

<script src="{{url_for('static',filename='javascript/landing.js')}}"></script>
{% endblock %}

loko/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="columns">
    <div class="column box is-two-fifths is-offset-one-fifth">
        <h1 class="title">Sign In</h1>
        <form action="" method="post" novalidate>
            {{ form.hidden_tag() }}
            <div class="field">
                {{ form.username.label(class="label") }}
                <div class="control">
                    {{ form.username(size=32, class="input", type="text") }}
                </div>
                {% for error in form.username.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="field">
                {{ form.password.label(class="label") }}
                <div class="control">
                    {{ form.password(size=32, class="input") }}<br>
                </div>
                {% for error in form.password.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="field">
                <div class="control">
                    {{ form.remember_me() }} {{ form.remember_me.label(class="checkbox") }}
                </div>
            </div>
            <div class="control">
                {{ form.submit(class="button is-link") }} 
            </div>
        </form>
        <p>New User? 
            <a href="{{ url_for('auth_blueprint.register') }}">
                <button class="button is-link is-light">Register</button>
            </a>
        </p>
    </div>
</div>
{% endblock %}

loko/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="columns">
    <div class="column box is-two-fifths is-offset-one-fifth">
        <h1 class="title">Register</h1>
        <form action="" method="post" novalidate>
            {{ form.hidden_tag() }}
            <div class="field">
                {{ form.name.label(class="label") }}
                <div class="control">
                    {{ form.name(size=32, class="input") }}
                </div>
                {% for error in form.name.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="field">
                {{ form.username.label(class="label") }}
                <div class="control">
                    {{ form.username(size=32, class="input", type="text") }}
                </div>
                {% for error in form.username.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="field">
                {{ form.email.label(class="label") }}
                <div class="control">
                    {{ form.email(size=32, class="input") }}<br>
                </div>
                {% for error in form.email.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="columns">
                <div class="field column is-three-fifths">
                    {{form.starting_balance.label()}}
                    <div class="control">
                        {{ form.starting_balance(size=32, class="input") }}<br>
                    </div>
                    {% for error in form.starting_balance.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
                <div class="field column">
                    {{ form.currency.label }}
                    <div class="select">
                        {{ form.currency() }}<br>
                    </div>
                    {% for error in form.currency.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
            </div>
            <div class="field">
                {{ form.password.label(class="label") }}
                <div class="control">
                    {{ form.password(size=32, class="input") }}
                </div>
                {% for error in form.password.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <div class="field">
                {{ form.password2.label(class="label") }}
                <div class="control">
                    {{ form.password2(size=32, class="input") }}<br>
                </div>
                {% for error in form.password2.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </div>
            <!-- Missing Accept terms field -->
            <div class="control">
                {{ form.submit(class="button is-link") }} 
            </div>
        </form>
        <p>Already have an account? 
            <a href="{{ url_for('auth_blueprint.login') }}">
                <button class="button is-link is-light">Sign in</button>
            </a>
        </p>
    </div>
</div>
{% endblock %}